# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Abdulrahman Khaledi
title: Computer Engineering Student
email: eng.ahkhaledi@gmail.com
# email_title: Email (Email title override)
phone: +966 58 012 0141
# phone_title: Phone (Phone title override)
website: Your website (eg. https://google.com)(optional)
website_title: Resume

# Dark Mode (true/false/never)
darkmode: never

# Social links
twitter_username: abdukhaledi
github_username:  abdukhaledi
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
linkedin_username: www.linkedin.com/in/abdulrahman-khaledi
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/me.jpg
about_content: | # this will include new lines to allow paragraphs
 Detail-oriented computer engineering student with a comprehensive understanding of Embedded Systems and Networks.
 Interested in a summer internship to enhance my skills and to learn production related theories to be applied in
 practical and grow in the field.
#   You can even add paragraphs by using empty lines like this and add anything else [markdown](https://www.markdownguide.org/getting-started#what-is-markdown) supports such as
#     - Lists
#     - Tables
#     - <a href="google.com">Links</a>
#     - Images ![alt text](/images/landscape-trees.jpg "Trees")

content:
  - title: Education
    layout: list
    content:
      - layout: right
        title: Umm AL-Qura University
        sub_title: Bachelor of Science, Computer Engineering
        caption: 2018 - 2023
        quote: >
        description: | # this will include new lines to allow paragraphs
          • GPA: 3.67 out of 4 "Second Honor" 
          
          • Member of IEEE and Computer club.
  - title: Experience
    layout: list
    content:
      - layout: right
        title: Smart Methods Company
        sub_title: Electronic Engineer
        caption: 6 Jul – 31 Sep 2021
#        link: https://mecai.org/cr/1000547862021/c/ac/ar.php?id=580120141&&cr=3
        quote: >
#          Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          •	Trained as Electronic Engineer.
          
          • Designed circuit, and wrote codes of four projects using Arduino, Tinkercad, and C++ language
          
          • Performed four missions, all have been used in robots those are commercially available.
          
          • Obtained recommendation letter from the CEO Eng. Wessam. 
  - title: Project1 # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Digital Thermometer Device
 #       link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
 #       link_text: Link Text
        additional_links:
          - title:  Github page for project
            icon: fab fa-github
            url: https://github.com/abdukhaledi/DigitalThermometer-Device
        quote: >
#          Short overview of the project (optional)
        description: | # this will include new lines to allow paragraphs
          •	Designed the circuit and wrote the code in C language
          
          •	Implemented PIC18F4550 microcontroller with LM35 temperature sensor and displayed the temperature on LCD 16x2.
  - title: Project2 # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left          
        title: 16-bit MIPS ALU
 #       link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
 #       link_text: Link Text
        additional_links:
          - title:  Github page for project
            icon: fab fa-github
            url: https://github.com/abdukhaledi/16-bit_MIPS_ALU
        quote: >
#          Short overview of the project (optional)
        description: | # this will include new lines to allow paragraphs
          •	Designed and simulated the circuit of 16-bit MIPS ALU and Control Unit using Logisim-evolution.
          
          •	16-bit ALU performed AND, OR, add, subtract, NOR and set less than operations. Control Unit performed R-format, lw, sw, beq instructions.
          
  - title: Activities
    layout: text
    content: | # this will include new lines to allow paragraphs
      •	Helped students as a tutor in many courses such as Programming Language, Object Oriented Language, and Microcomputers.

      •	Active member in Alpha Team on Twitter with over than 500 followers. Offering help and advice to freshman students in computer majors CS, IS, and CE.

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme #(Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
